cursor #f5ded6
cursor_text_color #dfc0b4

foreground            #f5ded6
background            #1c110c
selection_foreground  #2c340e
selection_background  #c2cb98
url_color             #adc6ff

color0   #1c110c
color1   #ff7299
color2   #7fff92
color3   #fff872
color4   #94b1f2
color5   #304576
color6   #adc6ff
color7   #eff4ff
color8   #999da5
color9   #ff9fb9
color10  #a5ffb3
color11  #fffaa5
color12  #b9ceff
color13  #c5d7ff
color14  #dae5ff
color15  #f8faff
