# Hyprland Configuration
########################################
# Hyprland Configuration (modular)
# https://wiki.hypr.land/Configuring/
########################################

# Each section is split into its own file for clarity and maintainability.
# Use 'source' to include them. Edit the referenced files for changes.

source = monitors.conf
source = env.conf
source = startup.conf
source = input.conf
source = layout.conf
source = decoration.conf
source = animations.conf
source = layouts.conf
source = misc.conf
source = windowrules.conf
source = keybindings.conf

source = ./dms/cursor.conf

source = ./dms/outputs.conf
