# ==================
# MONITOR CONFIG
# ==================
# monitor = monitor_name, resolution@refresh_rate, position, scale, vrr, <vrr_value> (0: off, 1: always on, 2: on with fullscreen apps)
# set vrr to override the global vrr setting in misc.conf

monitor = DP-2, 1920x1080@240, 1920x0, 1, vrr, 2
monitor = HDMI-A-1, 1920x1080@60, 0x0, 1, vrr, 0
