# ==================
# STARTUP APPS
# ==================
exec-once = bash -c "wl-paste --watch cliphist store &" # Start clipboard manager
exec-once = dms run # Start DankMaterialShell
exec-once = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 # Start polkit authentication agent
exec-once = hyprctl setcursor Bibata-Modern-Classic 20
exec-once = noisetorch -i
exec-once = /usr/bin/pypr

# ==================
# WORKSPACES
# ==================
# Initialize persistent workspaces on specific monitors
# workspace = workspace_number, persistent (true/false), monitor (monitor_name)

# Workspaces 1-5 on HDMI-A-1 (secondary monitor)
workspace=1,persistent:true,monitor:HDMI-A-1
workspace=2,persistent:true,monitor:HDMI-A-1
workspace=3,persistent:true,monitor:HDMI-A-1
workspace=4,persistent:true,monitor:HDMI-A-1
workspace=5,persistent:true,monitor:HDMI-A-1

# Workspaces 6-10 on DP-2 (main monitor)
workspace=6,persistent:true,monitor:DP-2,default true
workspace=7,persistent:true,monitor:DP-2
workspace=8,persistent:true,monitor:DP-2
workspace=9,persistent:true,monitor:DP-2
workspace=10,persistent:true,monitor:DP-2

# ==================
# AUTOSTART APPS ON SPECIFIC WORKSPACES
# ==================
# exec-once = [workspace <number> silent] <application>
exec-once=[workspace 1 silent] kitty -e btop
# exec-once=[workspace 2 silent] discord-canary
exec-once=[workspace 6 silent] zen-browser
exec-once=[workspace 8 silent] steam -silent
