# ==================
# WINDOW RULES
# ==================
windowrulev2 = tile, class:^(org\.wezfurlong\.wezterm)$
windowrulev2 = rounding 12, class:^(org\.gnome\.)
windowrulev2 = noborder, class:^(org\.gnome\.)
windowrulev2 = tile, class:^(gnome-control-center)$
windowrule = tile true, match:class ^(pavucontrol)$
windowrulev2 = tile, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(gnome-calculator)$
windowrulev2 = float, class:^(galculator)$
windowrule = float true, match:class ^(blueman-manager)$
windowrulev2 = float, class:^(org\.gnome\.Nautilus)$
windowrule = float true, match:class ^(steam)$
windowrule = tile true, match:class steam, match:title Steam
windowrulev2 = noborder, class:^(org\.wezfurlong\.wezterm)$
windowrulev2 = noborder, class:^(Alacritty)$
windowrulev2 = noborder, class:^(zen)$
windowrulev2 = noborder, class:^(com\.mitchellh\.ghostty)$
windowrule = border_size 0, match:class ^(kitty)$
windowrule = float true, match:class ^(kitty-dropterm)$
windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrule = float true, size 600 338, match:class ^(zen)$, match:title ^(Picture-in-Picture)$
windowrule = float true, match:class ^(zoom)$
windowrule = float true, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float true, match:class ^(xdg-desktop-portal)$
layerrule = no_anim on, match:namespace quickshell
windowrule = float true, match:class org.quickshell

# ==================
# Opacity Rules
# ==================
windowrule = opacity 0.9 0.9, match:float false, match:focus false # Unfocused windows are slightly transparent - Keep this as the first opacity rule
windowrulev2 = opacity 1.0 override 1.0 override, class:^(firefox)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(zen)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(mpv)$
windowrulev2 = opacity 0.95, class:^(code)$
